---
- hosts: all
  sudo: yes
  roles:
          - common

- hosts: primary
  sudo: yes
  roles:
          - primary
          - machine

- hosts: secondary
  sudo: yes
  roles:
          - secondary
          - machine

